//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.04 at 07:10:05 PM MESZ
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.opentrainingcenter.tcx;

