//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.09.04 at 07:10:05 PM MESZ
//

package ch.iseli.sportanalyzer.tcx;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for BuildType_t.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="BuildType_t">
 *   &lt;restriction base="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Token_t">
 *     &lt;enumeration value="Internal"/>
 *     &lt;enumeration value="Alpha"/>
 *     &lt;enumeration value="Beta"/>
 *     &lt;enumeration value="Release"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BuildType_t")
@XmlEnum
public enum BuildTypeT {

    @XmlEnumValue("Internal")
    INTERNAL("Internal"), @XmlEnumValue("Alpha")//$NON-NLS-1$
    ALPHA("Alpha"), @XmlEnumValue("Beta")//$NON-NLS-1$
    BETA("Beta"), @XmlEnumValue("Release")//$NON-NLS-1$
    RELEASE("Release");//$NON-NLS-1$
    private final String value;

    BuildTypeT(final String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BuildTypeT fromValue(final String v) {
        for (final BuildTypeT c : BuildTypeT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
