package ch.opentrainingcenter.transfer.impl;

import java.util.HashSet;
import java.util.Set;

import ch.opentrainingcenter.transfer.IAthlete;

/**
 * Athlete generated by hbm2java
 */
public class Athlete implements java.io.Serializable, IAthlete {

    private static final long serialVersionUID = 1L;
    private int id;
    private String name;
    private Set<Health> healths = new HashSet<Health>(0);
    private Set<Imported> importeds = new HashSet<Imported>(0);

    public Athlete() {
    }

    public Athlete(String name) {
        this.name = name;
    }

    public Athlete(int id) {
        this.id = id;
    }

    public Athlete(int id, String name, Set<Health> healths, Set<Imported> importeds) {
        this.id = id;
        this.name = name;
        this.healths = healths;
        this.importeds = importeds;
    }

    /*
     * (non-Javadoc)
     * 
     * @see ch.opentrainingcenter.transfer.internal.IAthlete#getId()
     */
    @Override
    public int getId() {
        return this.id;
    }

    /*
     * (non-Javadoc)
     * 
     * @see ch.opentrainingcenter.transfer.internal.IAthlete#setId(int)
     */
    @Override
    public void setId(int id) {
        this.id = id;
    }

    /*
     * (non-Javadoc)
     * 
     * @see ch.opentrainingcenter.transfer.internal.IAthlete#getName()
     */
    @Override
    public String getName() {
        return this.name;
    }

    /*
     * (non-Javadoc)
     * 
     * @see ch.opentrainingcenter.transfer.internal.IAthlete#setName(java.lang.String)
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /*
     * (non-Javadoc)
     * 
     * @see ch.opentrainingcenter.transfer.internal.IAthlete#getHealths()
     */
    @Override
    public Set<Health> getHealths() {
        return this.healths;
    }

    /*
     * (non-Javadoc)
     * 
     * @see ch.opentrainingcenter.transfer.internal.IAthlete#setHealths(java.util.Set)
     */
    @Override
    public void setHealths(Set<Health> healths) {
        this.healths = healths;
    }

    /*
     * (non-Javadoc)
     * 
     * @see ch.opentrainingcenter.transfer.internal.IAthlete#getImporteds()
     */
    @Override
    public Set<Imported> getImporteds() {
        return this.importeds;
    }

    /*
     * (non-Javadoc)
     * 
     * @see ch.opentrainingcenter.transfer.internal.IAthlete#setImporteds(java.util.Set)
     */
    @Override
    public void setImporteds(Set<Imported> importeds) {
        this.importeds = importeds;
    }

    @Override
    public String toString() {
        return "Athlete [id=" + id + ", name=" + name + ", importeds=" + importeds.size() + "]";
    }

}
