package ch.opentrainingcenter.transfer.impl;

// Generated 04.04.2013 20:38:06 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import ch.opentrainingcenter.transfer.IAthlete;
import ch.opentrainingcenter.transfer.IHealth;
import ch.opentrainingcenter.transfer.IPlanungWoche;
import ch.opentrainingcenter.transfer.IRoute;
import ch.opentrainingcenter.transfer.ITraining;

/**
 * Athlete generated by hbm2java
 */
public class Athlete implements java.io.Serializable, IAthlete {
    private static final long serialVersionUID = 1L;
    private int id;
    private String name;
    private int age;
    private Integer maxheartrate;
    private Set<IRoute> routes = new HashSet<IRoute>(0);
    private Set<IHealth> healths = new HashSet<IHealth>(0);
    private Set<ITraining> trainings = new HashSet<ITraining>(0);
    private Set<IPlanungWoche> planungwoches = new HashSet<IPlanungWoche>(0);

    public Athlete() {
    }

    public Athlete(final int id, final int age) {
        this.id = id;
        this.age = age;
    }

    public Athlete(final int id, final String name, final int age, final Integer maxheartrate, final Set<IRoute> routes, final Set<IHealth> healths,
            final Set<ITraining> trainings, final Set<IPlanungWoche> planungwoches) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.maxheartrate = maxheartrate;
        this.routes = routes;
        this.healths = healths;
        this.trainings = trainings;
        this.planungwoches = planungwoches;
    }

    public Athlete(final String name, final Integer age, final Integer maxHeartBeat) {
        this.name = name;
        this.age = age;
        maxheartrate = maxHeartBeat;
    }

    @Override
    public int getId() {
        return this.id;
    }

    @Override
    public void setId(final int id) {
        this.id = id;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(final String name) {
        this.name = name;
    }

    @Override
    public Integer getAge() {
        return this.age;
    }

    public void setAge(final int age) {
        this.age = age;
    }

    public Integer getMaxheartrate() {
        return this.maxheartrate;
    }

    public void setMaxheartrate(final Integer maxheartrate) {
        this.maxheartrate = maxheartrate;
    }

    public Set<IRoute> getRoutes() {
        return this.routes;
    }

    public void setRoutes(final Set<IRoute> routes) {
        this.routes = routes;
    }

    public Set<IPlanungWoche> getPlanungwoches() {
        return this.planungwoches;
    }

    public void setPlanungwoches(final Set<IPlanungWoche> planungwoches) {
        this.planungwoches = planungwoches;
    }

    @Override
    public void addTraining(final ITraining record) {
        trainings.add(record);
    }

    @Override
    public Integer getMaxHeartRate() {
        return maxheartrate;
    }

    @Override
    public void setMaxHeartRate(final Integer maxHeartRate) {
        maxheartrate = maxHeartRate;

    }

    @Override
    public Set<IHealth> getHealths() {
        return healths;
    }

    @Override
    public void setHealths(final Set<IHealth> healths) {
        this.healths = healths;
    }

    @Override
    public Set<ITraining> getTrainings() {
        return null;
    }

    @Override
    public void setTrainings(final Set<ITraining> trainings) {
        this.trainings = trainings;

    }

    @Override
    public void setAge(final Integer age) {
        this.age = age;
    }

}
