package ch.opentrainingcenter.transfer.impl;

// default package
// Generated 21.10.2011 12:19:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import ch.opentrainingcenter.transfer.IAthlete;
import ch.opentrainingcenter.transfer.IHealth;

/**
 * Health generated by hbm2java
 */
public class Health implements java.io.Serializable, IHealth {

    private static final long serialVersionUID = 1L;
    private int id;
    private IAthlete athlete;
    private Double weight;
    private Integer cardio;
    private Date dateofmeasure;

    /**
     * nur für hibernate
     */
    public Health() {
    }

    public Health(final IAthlete athlete, final Double weight, final Integer cardio, final Date dateofmeasure) {
        this.athlete = athlete;
        this.weight = weight;
        this.cardio = cardio;
        this.dateofmeasure = dateofmeasure;
    }

    @Override
    public int getId() {
        return this.id;
    }

    @Override
    public void setId(final int id) {
        this.id = id;
    }

    @Override
    public IAthlete getAthlete() {
        return this.athlete;
    }

    @Override
    public void setAthlete(final IAthlete athlete) {
        this.athlete = athlete;
    }

    @Override
    public Double getWeight() {
        return this.weight;
    }

    @Override
    public void setWeight(final Double weight) {
        this.weight = weight;
    }

    @Override
    public Integer getCardio() {
        return this.cardio;
    }

    @Override
    public void setCardio(final Integer cardio) {
        this.cardio = cardio;
    }

    @Override
    public Date getDateofmeasure() {
        return this.dateofmeasure;
    }

    @Override
    public void setDateofmeasure(final Date dateofmeasure) {
        this.dateofmeasure = dateofmeasure;
    }

    @Override
    public String toString() {
        return "Health [id=" + id + ", athlete=" + athlete + ", weight=" + weight + ", cardio=" + cardio + ", dateofmeasure=" //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$ //$NON-NLS-5$
                + dateofmeasure + "]"; //$NON-NLS-1$
    }
}
