package ch.opentrainingcenter.transfer.impl;

// default package
// Generated 21.10.2011 12:19:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import ch.opentrainingcenter.transfer.IAthlete;
import ch.opentrainingcenter.transfer.IImported;
import ch.opentrainingcenter.transfer.IWeather;

/**
 * Imported generated by hbm2java
 */
public class Imported implements java.io.Serializable, IImported {

    private static final long serialVersionUID = 1L;
    private int id;
    private IWeather weather;
    private IAthlete athlete;
    private Date importedDate;
    private String comments;

    public Imported() {
    }

    public Imported(int id) {
        this.id = id;
    }

    public Imported(int id, IWeather weather, IAthlete athlete, Date importedDate, String comments) {
        this.id = id;
        this.weather = weather;
        this.athlete = athlete;
        this.importedDate = importedDate;
        this.comments = comments;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#getId()
     */
    @Override
    public int getId() {
        return this.id;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#setId(int)
     */
    @Override
    public void setId(int id) {
        this.id = id;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#getWeather()
     */
    @Override
    public IWeather getWeather() {
        return this.weather;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#setWeather(ch.opentrainingcenter.transfer.internal.Weather)
     */
    @Override
    public void setWeather(IWeather weather) {
        this.weather = weather;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#getAthlete()
     */
    @Override
    public IAthlete getAthlete() {
        return this.athlete;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#setAthlete(ch.opentrainingcenter.transfer.IAthlete)
     */
    @Override
    public void setAthlete(IAthlete athlete) {
        this.athlete = athlete;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#getImportedDate()
     */
    @Override
    public Date getImportedDate() {
        return this.importedDate;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#setImportedDate(java.util.Date)
     */
    @Override
    public void setImportedDate(Date importedDate) {
        this.importedDate = importedDate;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#getComments()
     */
    @Override
    public String getComments() {
        return this.comments;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IImported#setComments(java.lang.String)
     */
    @Override
    public void setComments(String comments) {
        this.comments = comments;
    }

}
