package ch.opentrainingcenter.transfer.impl;

import ch.opentrainingcenter.transfer.IAthlete;
import ch.opentrainingcenter.transfer.IRoute;

// Generated 04.04.2013 20:38:06 by Hibernate Tools 3.4.0.CR1

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable, IRoute {

    private static final long serialVersionUID = 1L;

    private int id;
    private String name;
    private String beschreibung;
    private IAthlete athlete;

    public Route() {
    }

    public Route(final String name, final String beschreibung) {
        this(name, beschreibung, null);
    }

    public Route(final String name, final String beschreibung, final IAthlete athlete) {
        this.name = name;
        this.beschreibung = beschreibung;
        this.athlete = athlete;
    }

    @Override
    public int getId() {
        return id;
    }

    @Override
    public void setId(final int id) {
        this.id = id;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(final String name) {
        this.name = name;
    }

    @Override
    public String getBeschreibung() {
        return this.beschreibung;
    }

    @Override
    public void setBeschreibung(final String beschreibung) {
        this.beschreibung = beschreibung;
    }

    @Override
    public void setAthlete(final IAthlete athlete) {
        this.athlete = athlete;
    }

    @Override
    public IAthlete getAthlete() {
        return athlete;
    }
}
