package ch.opentrainingcenter.transfer.impl;

// Generated 04.04.2013 20:38:06 by Hibernate Tools 3.4.0.CR1

import ch.opentrainingcenter.transfer.ITrainingType;

/**
 * Trainingtype generated by hbm2java
 */
public class Trainingtype implements java.io.Serializable, ITrainingType {

    private static final long serialVersionUID = 1L;
    private int id;
    private String title;
    private String description;
    private String imageicon;

    // private Set<ITraining> trainings = new HashSet<ITraining>(0);

    public Trainingtype() {
    }

    public Trainingtype(final int id, final String title, final String description) {
        this.id = id;
        this.title = title;
        this.description = description;
    }

    @Override
    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    public void setTitle(final String title) {
        this.title = title;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    @Override
    public String getImageicon() {
        return this.imageicon;
    }

    public void setImageicon(final String imageicon) {
        this.imageicon = imageicon;
    }

    //
    // @Override
    // public Set<ITraining> getTrainings() {
    // return this.trainings;
    // }
    //
    // public void setTrainings(final Set<ITraining> trainings) {
    // this.trainings = trainings;
    // }

    @SuppressWarnings("nls")
    @Override
    public String toString() {
        return "Trainingtype [title=" + title + ", description=" + description + ", imageicon=" + imageicon + "]";
    }

}
