package ch.opentrainingcenter.transfer.impl;

// default package
// Generated 21.10.2011 12:19:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import ch.opentrainingcenter.transfer.ITraining;
import ch.opentrainingcenter.transfer.IWeather;

/**
 * Weather generated by hbm2java
 */
public class Weather implements java.io.Serializable, IWeather {

    private static final long serialVersionUID = 1L;
    private int id;
    private String wetter;
    private String imageIcon;
    private Set<ITraining> trainings = new HashSet<ITraining>(0);

    public Weather() {
    }

    public Weather(final int id) {
        this.id = id;
    }

    public Weather(final int id, final String wetter, final Set<ITraining> trainings) {
        this.id = id;
        this.wetter = wetter;
        this.trainings = trainings;
    }

    /*
     * (non-Javadoc)
     * 
     * @see ch.opentrainingcenter.transfer.internal.IWeather#getId()
     */
    @Override
    public int getId() {
        return this.id;
    }

    public void setId(final int id) {
        this.id = id;
    }

    @Override
    public String getWetter() {
        return this.wetter;
    }

    public void setWetter(final String wetter) {
        this.wetter = wetter;
    }

    @Override
    public Set<ITraining> getTrainings() {
        return this.trainings;
    }

    public void setTrainings(final Set<ITraining> importeds) {
        this.trainings = importeds;
    }

    public String getImageIcon() {
        return imageIcon;
    }

    public void setImageIcon(final String imageIcon) {
        this.imageIcon = imageIcon;
    }
}
