//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.11 at 09:02:07 AM CET 
//


package ch.opentrainingcenter.importer.fitnesslog.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Metadata" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Duration" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Distance" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Elevation" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}HeartRate" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Cadence" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Power" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Calories" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Laps" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Intensity" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Weather" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Category" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Location" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Route" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}EquipmentUsed" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}Track" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}TrackClock" minOccurs="0"/>
 *         &lt;element ref="{http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2}DistanceMarkers" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="StartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "duration",
    "distance",
    "elevation",
    "heartRate",
    "cadence",
    "power",
    "calories",
    "notes",
    "name",
    "laps",
    "intensity",
    "weather",
    "category",
    "location",
    "route",
    "equipmentUsed",
    "track",
    "trackClock",
    "distanceMarkers"
})
@XmlRootElement(name = "Activity")
public class Activity {

    @XmlElement(name = "Metadata")
    protected Metadata metadata;
    @XmlElement(name = "Duration")
    protected Duration duration;
    @XmlElement(name = "Distance")
    protected Distance distance;
    @XmlElement(name = "Elevation")
    protected Elevation elevation;
    @XmlElement(name = "HeartRate")
    protected HeartRate heartRate;
    @XmlElement(name = "Cadence")
    protected Cadence cadence;
    @XmlElement(name = "Power")
    protected Power power;
    @XmlElement(name = "Calories")
    protected Calories calories;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Laps")
    protected Laps laps;
    @XmlElement(name = "Intensity")
    protected Intensity intensity;
    @XmlElement(name = "Weather")
    protected Weather weather;
    @XmlElement(name = "Category")
    protected Category category;
    @XmlElement(name = "Location")
    protected Location location;
    @XmlElement(name = "Route")
    protected Route route;
    @XmlElement(name = "EquipmentUsed")
    protected EquipmentUsed equipmentUsed;
    @XmlElement(name = "Track")
    protected Track track;
    @XmlElement(name = "TrackClock")
    protected TrackClock trackClock;
    @XmlElement(name = "DistanceMarkers")
    protected DistanceMarkers distanceMarkers;
    @XmlAttribute(name = "StartTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlAttribute(name = "Id", required = true)
    protected String id;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Metadata }
     *     
     */
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Metadata }
     *     
     */
    public void setMetadata(Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link Distance }
     *     
     */
    public Distance getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Distance }
     *     
     */
    public void setDistance(Distance value) {
        this.distance = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return
     *     possible object is
     *     {@link Elevation }
     *     
     */
    public Elevation getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Elevation }
     *     
     */
    public void setElevation(Elevation value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the heartRate property.
     * 
     * @return
     *     possible object is
     *     {@link HeartRate }
     *     
     */
    public HeartRate getHeartRate() {
        return heartRate;
    }

    /**
     * Sets the value of the heartRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeartRate }
     *     
     */
    public void setHeartRate(HeartRate value) {
        this.heartRate = value;
    }

    /**
     * Gets the value of the cadence property.
     * 
     * @return
     *     possible object is
     *     {@link Cadence }
     *     
     */
    public Cadence getCadence() {
        return cadence;
    }

    /**
     * Sets the value of the cadence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cadence }
     *     
     */
    public void setCadence(Cadence value) {
        this.cadence = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link Power }
     *     
     */
    public Power getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link Power }
     *     
     */
    public void setPower(Power value) {
        this.power = value;
    }

    /**
     * Gets the value of the calories property.
     * 
     * @return
     *     possible object is
     *     {@link Calories }
     *     
     */
    public Calories getCalories() {
        return calories;
    }

    /**
     * Sets the value of the calories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calories }
     *     
     */
    public void setCalories(Calories value) {
        this.calories = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the laps property.
     * 
     * @return
     *     possible object is
     *     {@link Laps }
     *     
     */
    public Laps getLaps() {
        return laps;
    }

    /**
     * Sets the value of the laps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Laps }
     *     
     */
    public void setLaps(Laps value) {
        this.laps = value;
    }

    /**
     * Gets the value of the intensity property.
     * 
     * @return
     *     possible object is
     *     {@link Intensity }
     *     
     */
    public Intensity getIntensity() {
        return intensity;
    }

    /**
     * Sets the value of the intensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intensity }
     *     
     */
    public void setIntensity(Intensity value) {
        this.intensity = value;
    }

    /**
     * Gets the value of the weather property.
     * 
     * @return
     *     possible object is
     *     {@link Weather }
     *     
     */
    public Weather getWeather() {
        return weather;
    }

    /**
     * Sets the value of the weather property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weather }
     *     
     */
    public void setWeather(Weather value) {
        this.weather = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link Route }
     *     
     */
    public Route getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link Route }
     *     
     */
    public void setRoute(Route value) {
        this.route = value;
    }

    /**
     * Gets the value of the equipmentUsed property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentUsed }
     *     
     */
    public EquipmentUsed getEquipmentUsed() {
        return equipmentUsed;
    }

    /**
     * Sets the value of the equipmentUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentUsed }
     *     
     */
    public void setEquipmentUsed(EquipmentUsed value) {
        this.equipmentUsed = value;
    }

    /**
     * Gets the value of the track property.
     * 
     * @return
     *     possible object is
     *     {@link Track }
     *     
     */
    public Track getTrack() {
        return track;
    }

    /**
     * Sets the value of the track property.
     * 
     * @param value
     *     allowed object is
     *     {@link Track }
     *     
     */
    public void setTrack(Track value) {
        this.track = value;
    }

    /**
     * Gets the value of the trackClock property.
     * 
     * @return
     *     possible object is
     *     {@link TrackClock }
     *     
     */
    public TrackClock getTrackClock() {
        return trackClock;
    }

    /**
     * Sets the value of the trackClock property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrackClock }
     *     
     */
    public void setTrackClock(TrackClock value) {
        this.trackClock = value;
    }

    /**
     * Gets the value of the distanceMarkers property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceMarkers }
     *     
     */
    public DistanceMarkers getDistanceMarkers() {
        return distanceMarkers;
    }

    /**
     * Sets the value of the distanceMarkers property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceMarkers }
     *     
     */
    public void setDistanceMarkers(DistanceMarkers value) {
        this.distanceMarkers = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
