//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.11 at 09:02:07 AM CET 
//


package ch.opentrainingcenter.importer.fitnesslog.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="WeightKilograms" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="BodyFatPercentage" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RestingHeartRateBPM" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="MaximumHeartRateBPM" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="SystolicBloodPressure" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="DiastolicBloodPressure" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="CaloriesConsumed" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="Mood" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SleepHours" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="SleepQuality" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Injured" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="InjuredText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sick" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SickText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MissedWorkout" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="MissedWorkoutText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "History")
public class History {

    @XmlAttribute(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "WeightKilograms")
    protected BigDecimal weightKilograms;
    @XmlAttribute(name = "BodyFatPercentage")
    protected BigDecimal bodyFatPercentage;
    @XmlAttribute(name = "RestingHeartRateBPM")
    protected BigDecimal restingHeartRateBPM;
    @XmlAttribute(name = "MaximumHeartRateBPM")
    protected BigDecimal maximumHeartRateBPM;
    @XmlAttribute(name = "SystolicBloodPressure")
    protected BigDecimal systolicBloodPressure;
    @XmlAttribute(name = "DiastolicBloodPressure")
    protected BigDecimal diastolicBloodPressure;
    @XmlAttribute(name = "CaloriesConsumed")
    protected BigDecimal caloriesConsumed;
    @XmlAttribute(name = "Mood")
    protected BigInteger mood;
    @XmlAttribute(name = "SleepHours")
    protected BigDecimal sleepHours;
    @XmlAttribute(name = "SleepQuality")
    protected BigInteger sleepQuality;
    @XmlAttribute(name = "Injured")
    protected Boolean injured;
    @XmlAttribute(name = "InjuredText")
    protected String injuredText;
    @XmlAttribute(name = "Sick")
    protected Boolean sick;
    @XmlAttribute(name = "SickText")
    protected String sickText;
    @XmlAttribute(name = "MissedWorkout")
    protected Boolean missedWorkout;
    @XmlAttribute(name = "MissedWorkoutText")
    protected String missedWorkoutText;
    @XmlAttribute(name = "Notes")
    protected String notes;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the weightKilograms property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeightKilograms() {
        return weightKilograms;
    }

    /**
     * Sets the value of the weightKilograms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeightKilograms(BigDecimal value) {
        this.weightKilograms = value;
    }

    /**
     * Gets the value of the bodyFatPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBodyFatPercentage() {
        return bodyFatPercentage;
    }

    /**
     * Sets the value of the bodyFatPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBodyFatPercentage(BigDecimal value) {
        this.bodyFatPercentage = value;
    }

    /**
     * Gets the value of the restingHeartRateBPM property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRestingHeartRateBPM() {
        return restingHeartRateBPM;
    }

    /**
     * Sets the value of the restingHeartRateBPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRestingHeartRateBPM(BigDecimal value) {
        this.restingHeartRateBPM = value;
    }

    /**
     * Gets the value of the maximumHeartRateBPM property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaximumHeartRateBPM() {
        return maximumHeartRateBPM;
    }

    /**
     * Sets the value of the maximumHeartRateBPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaximumHeartRateBPM(BigDecimal value) {
        this.maximumHeartRateBPM = value;
    }

    /**
     * Gets the value of the systolicBloodPressure property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSystolicBloodPressure() {
        return systolicBloodPressure;
    }

    /**
     * Sets the value of the systolicBloodPressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSystolicBloodPressure(BigDecimal value) {
        this.systolicBloodPressure = value;
    }

    /**
     * Gets the value of the diastolicBloodPressure property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiastolicBloodPressure() {
        return diastolicBloodPressure;
    }

    /**
     * Sets the value of the diastolicBloodPressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiastolicBloodPressure(BigDecimal value) {
        this.diastolicBloodPressure = value;
    }

    /**
     * Gets the value of the caloriesConsumed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCaloriesConsumed() {
        return caloriesConsumed;
    }

    /**
     * Sets the value of the caloriesConsumed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCaloriesConsumed(BigDecimal value) {
        this.caloriesConsumed = value;
    }

    /**
     * Gets the value of the mood property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMood() {
        return mood;
    }

    /**
     * Sets the value of the mood property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMood(BigInteger value) {
        this.mood = value;
    }

    /**
     * Gets the value of the sleepHours property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSleepHours() {
        return sleepHours;
    }

    /**
     * Sets the value of the sleepHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSleepHours(BigDecimal value) {
        this.sleepHours = value;
    }

    /**
     * Gets the value of the sleepQuality property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSleepQuality() {
        return sleepQuality;
    }

    /**
     * Sets the value of the sleepQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSleepQuality(BigInteger value) {
        this.sleepQuality = value;
    }

    /**
     * Gets the value of the injured property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInjured() {
        return injured;
    }

    /**
     * Sets the value of the injured property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInjured(Boolean value) {
        this.injured = value;
    }

    /**
     * Gets the value of the injuredText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInjuredText() {
        return injuredText;
    }

    /**
     * Sets the value of the injuredText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInjuredText(String value) {
        this.injuredText = value;
    }

    /**
     * Gets the value of the sick property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSick() {
        return sick;
    }

    /**
     * Sets the value of the sick property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSick(Boolean value) {
        this.sick = value;
    }

    /**
     * Gets the value of the sickText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSickText() {
        return sickText;
    }

    /**
     * Sets the value of the sickText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSickText(String value) {
        this.sickText = value;
    }

    /**
     * Gets the value of the missedWorkout property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMissedWorkout() {
        return missedWorkout;
    }

    /**
     * Sets the value of the missedWorkout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMissedWorkout(Boolean value) {
        this.missedWorkout = value;
    }

    /**
     * Gets the value of the missedWorkoutText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissedWorkoutText() {
        return missedWorkoutText;
    }

    /**
     * Sets the value of the missedWorkoutText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissedWorkoutText(String value) {
        this.missedWorkoutText = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

}
