//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.11 at 09:02:07 AM CET 
//


package ch.opentrainingcenter.importer.fitnesslog.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.opentrainingcenter.importer.fitnesslog package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.opentrainingcenter.importer.fitnesslog
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Calories }
     * 
     */
    public Calories createCalories() {
        return new Calories();
    }

    /**
     * Create an instance of {@link EquipmentItem }
     * 
     */
    public EquipmentItem createEquipmentItem() {
        return new EquipmentItem();
    }

    /**
     * Create an instance of {@link AthleteLog }
     * 
     */
    public AthleteLog createAthleteLog() {
        return new AthleteLog();
    }

    /**
     * Create an instance of {@link Athlete }
     * 
     */
    public Athlete createAthlete() {
        return new Athlete();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Duration }
     * 
     */
    public Duration createDuration() {
        return new Duration();
    }

    /**
     * Create an instance of {@link Distance }
     * 
     */
    public Distance createDistance() {
        return new Distance();
    }

    /**
     * Create an instance of {@link Elevation }
     * 
     */
    public Elevation createElevation() {
        return new Elevation();
    }

    /**
     * Create an instance of {@link HeartRate }
     * 
     */
    public HeartRate createHeartRate() {
        return new HeartRate();
    }

    /**
     * Create an instance of {@link Cadence }
     * 
     */
    public Cadence createCadence() {
        return new Cadence();
    }

    /**
     * Create an instance of {@link Power }
     * 
     */
    public Power createPower() {
        return new Power();
    }

    /**
     * Create an instance of {@link Laps }
     * 
     */
    public Laps createLaps() {
        return new Laps();
    }

    /**
     * Create an instance of {@link Lap }
     * 
     */
    public Lap createLap() {
        return new Lap();
    }

    /**
     * Create an instance of {@link Intensity }
     * 
     */
    public Intensity createIntensity() {
        return new Intensity();
    }

    /**
     * Create an instance of {@link Weather }
     * 
     */
    public Weather createWeather() {
        return new Weather();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link EquipmentUsed }
     * 
     */
    public EquipmentUsed createEquipmentUsed() {
        return new EquipmentUsed();
    }

    /**
     * Create an instance of {@link Track }
     * 
     */
    public Track createTrack() {
        return new Track();
    }

    /**
     * Create an instance of {@link Pt }
     * 
     */
    public Pt createPt() {
        return new Pt();
    }

    /**
     * Create an instance of {@link TrackClock }
     * 
     */
    public TrackClock createTrackClock() {
        return new TrackClock();
    }

    /**
     * Create an instance of {@link Pause }
     * 
     */
    public Pause createPause() {
        return new Pause();
    }

    /**
     * Create an instance of {@link DistanceMarkers }
     * 
     */
    public DistanceMarkers createDistanceMarkers() {
        return new DistanceMarkers();
    }

    /**
     * Create an instance of {@link Marker }
     * 
     */
    public Marker createMarker() {
        return new Marker();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link FitnessWorkbook }
     * 
     */
    public FitnessWorkbook createFitnessWorkbook() {
        return new FitnessWorkbook();
    }

}
