//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.11 at 09:02:07 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.opentrainingcenter.importer.fitnesslog.model;
