package ch.opentrainingcenter.transfer.internal;

// default package
// Generated 21.10.2011 12:19:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import ch.opentrainingcenter.transfer.IAthlete;
import ch.opentrainingcenter.transfer.IHealth;

/**
 * Health generated by hbm2java
 */
public class Health implements java.io.Serializable, IHealth {

    private static final long serialVersionUID = 1L;
    private int id;
    private IAthlete athlete;
    private Integer weight;
    private Integer cardio;
    private Date dateofmeasure;

    public Health() {
    }

    public Health(int id) {
        this.id = id;
    }

    public Health(int id, IAthlete athlete, Integer weight, Integer cardio, Date dateofmeasure) {
        this.id = id;
        this.athlete = athlete;
        this.weight = weight;
        this.cardio = cardio;
        this.dateofmeasure = dateofmeasure;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#getId()
     */
    @Override
    public int getId() {
        return this.id;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#setId(int)
     */
    @Override
    public void setId(int id) {
        this.id = id;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#getAthlete()
     */
    @Override
    public IAthlete getAthlete() {
        return this.athlete;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#setAthlete(ch.opentrainingcenter.transfer.IAthlete)
     */
    @Override
    public void setAthlete(IAthlete athlete) {
        this.athlete = athlete;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#getWeight()
     */
    @Override
    public Integer getWeight() {
        return this.weight;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#setWeight(java.lang.Integer)
     */
    @Override
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#getCardio()
     */
    @Override
    public Integer getCardio() {
        return this.cardio;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#setCardio(java.lang.Integer)
     */
    @Override
    public void setCardio(Integer cardio) {
        this.cardio = cardio;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#getDateofmeasure()
     */
    @Override
    public Date getDateofmeasure() {
        return this.dateofmeasure;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IHealth#setDateofmeasure(java.util.Date)
     */
    @Override
    public void setDateofmeasure(Date dateofmeasure) {
        this.dateofmeasure = dateofmeasure;
    }

}
