package ch.opentrainingcenter.transfer.internal;

// default package
// Generated 21.10.2011 12:19:41 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import ch.opentrainingcenter.transfer.IImported;
import ch.opentrainingcenter.transfer.IWeather;

/**
 * Weather generated by hbm2java
 */
public class Weather implements java.io.Serializable, IWeather {

    private static final long serialVersionUID = 1L;
    private int id;
    private String wetter;
    private Set<IImported> importeds = new HashSet<IImported>(0);

    public Weather() {
    }

    public Weather(int id) {
        this.id = id;
    }

    public Weather(int id, String wetter, Set<IImported> importeds) {
        this.id = id;
        this.wetter = wetter;
        this.importeds = importeds;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IWeather#getId()
     */
    @Override
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IWeather#getWetter()
     */
    @Override
    public String getWetter() {
        return this.wetter;
    }

    public void setWetter(String wetter) {
        this.wetter = wetter;
    }

    /* (non-Javadoc)
     * @see ch.opentrainingcenter.transfer.internal.IWeather#getImporteds()
     */
    @Override
    public Set<IImported> getImporteds() {
        return this.importeds;
    }

    public void setImporteds(Set<IImported> importeds) {
        this.importeds = importeds;
    }

}
