--------------------------------------------------------
--  DDL for Table ATHLETE
--------------------------------------------------------

  CREATE TABLE "OTC"."ATHLETE" 
   (	"ID" NUMBER(5,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"BIRTHDAY" DATE, 
	"MAXHEARTRATE" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HEALTH
--------------------------------------------------------

  CREATE TABLE "OTC"."HEALTH" 
   (	"ID" NUMBER(9,0), 
	"WEIGHT" NUMBER(*,0), 
	"CARDIO" NUMBER(*,0), 
	"DATEOFMEASURE" DATE, 
	"ID_FK_ATHLETE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LAPINFO
--------------------------------------------------------

  CREATE TABLE "OTC"."LAPINFO" 
   (	"ID" NUMBER(18,0), 
	"LAP_START" NUMBER(9,0), 
	"LAP_END" NUMBER(9,0), 
	"HEARTBEAT" NUMBER(3,0), 
	"PACE" VARCHAR2(100 BYTE), 
	"GESCHWINDIGKEIT" VARCHAR2(100 BYTE), 
	"TIME" NUMBER(9,0), 
	"LAP" NUMBER(5,0), 
	"IDX" NUMBER(9,0), 
	"ID_TRAINING" NUMBER(32,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PLANUNGWOCHE
--------------------------------------------------------

  CREATE TABLE "OTC"."PLANUNGWOCHE" 
   (	"ID" NUMBER(9,0), 
	"KW" NUMBER(3,0), 
	"JAHR" NUMBER(5,0), 
	"KMPROWOCHE" NUMBER(5,0), 
	"INTERVAL" NUMBER(1,0), 
	"LANGERLAUF" NUMBER(9,0), 
	"ID_FK_ATHLETE" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROUTE
--------------------------------------------------------

  CREATE TABLE "OTC"."ROUTE" 
   (	"ID" NUMBER(9,0), 
	"ID_FK_ATHLETE" NUMBER(9,0), 
	"ID_FK_TRAINING" NUMBER(18,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"BESCHREIBUNG" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SHOES
--------------------------------------------------------

  CREATE TABLE "OTC"."SHOES" 
   (	"ID" NUMBER(5,0), 
	"SCHUHNAME" VARCHAR2(1000 BYTE), 
	"IMAGEICON" VARCHAR2(1000 BYTE), 
	"PREIS" NUMBER(3,0), 
	"KAUFDATUM" TIMESTAMP (6), 
	"ID_FK_ATHLETE" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STRECKENPUNKTE
--------------------------------------------------------

  CREATE TABLE "OTC"."STRECKENPUNKTE" 
   (	"ID" NUMBER(32,0), 
	"LONGITUDE" NUMBER(32,26), 
	"LATITUDE" NUMBER(32,26)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRACKTRAININGPROPERTY
--------------------------------------------------------

  CREATE TABLE "OTC"."TRACKTRAININGPROPERTY" 
   (	"ID" NUMBER(32,0), 
	"DISTANCE" NUMBER(28,18), 
	"HEARTBEAT" NUMBER(3,0), 
	"ALTITUDE" NUMBER(5,0), 
	"ZEIT" NUMBER(18,0), 
	"LAP" NUMBER(4,0), 
	"ID_FK_STRECKENPUNKT" NUMBER(32,0), 
	"IDX" NUMBER(5,0), 
	"ID_TRAINING" NUMBER(32,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRAINING
--------------------------------------------------------

  CREATE TABLE "OTC"."TRAINING" 
   (	"ID_TRAINING" NUMBER(*,0), 
	"DATUM" NUMBER(14,0), 
	"DAUER" NUMBER(7,1), 
	"LAENGEINMETER" NUMBER(7,1), 
	"AVERAGEHEARTBEAT" NUMBER(3,0), 
	"MAXHEARTBEAT" NUMBER(3,0), 
	"MAXSPEED" NUMBER(24,14), 
	"NOTE" VARCHAR2(1000 BYTE), 
	"DATEOFIMPORT" TIMESTAMP (6), 
	"FILENAME" VARCHAR2(500 BYTE), 
	"UPMETER" NUMBER(3,0), 
	"DOWNMETER" NUMBER(3,0), 
	"GEO_QUALITY" NUMBER(3,0), 
	"TRAINING_EFFECT" NUMBER(2,0), 
	"ID_FK_WEATHER" NUMBER(5,0), 
	"ID_FK_ROUTE" NUMBER(5,0), 
	"ID_FK_ATHLETE" NUMBER(5,0), 
	"ID_FK_SHOES" NUMBER(5,0), 
	"TRAININGTYPE" NUMBER(2,0), 
	"SPORT" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table WEATHER
--------------------------------------------------------

  CREATE TABLE "OTC"."WEATHER" 
   (	"ID" NUMBER(2,0), 
	"WETTER" VARCHAR2(255 BYTE), 
	"IMAGEICON" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007094
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007094" ON "OTC"."ATHLETE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007125
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007125" ON "OTC"."ATHLETE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007096
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007096" ON "OTC"."HEALTH" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007108
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007108" ON "OTC"."LAPINFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007100
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007100" ON "OTC"."PLANUNGWOCHE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007102
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007102" ON "OTC"."ROUTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007114
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007114" ON "OTC"."SHOES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007104
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007104" ON "OTC"."STRECKENPUNKTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007106
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007106" ON "OTC"."TRACKTRAININGPROPERTY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007112
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007112" ON "OTC"."TRAINING" ("ID_TRAINING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007098
--------------------------------------------------------

  CREATE UNIQUE INDEX "OTC"."SYS_C007098" ON "OTC"."WEATHER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATHLETE
--------------------------------------------------------

  ALTER TABLE "OTC"."ATHLETE" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."ATHLETE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."ATHLETE" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "OTC"."ATHLETE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HEALTH
--------------------------------------------------------

  ALTER TABLE "OTC"."HEALTH" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."HEALTH" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LAPINFO
--------------------------------------------------------

  ALTER TABLE "OTC"."LAPINFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."LAPINFO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANUNGWOCHE
--------------------------------------------------------

  ALTER TABLE "OTC"."PLANUNGWOCHE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."PLANUNGWOCHE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROUTE
--------------------------------------------------------

  ALTER TABLE "OTC"."ROUTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."ROUTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOES
--------------------------------------------------------

  ALTER TABLE "OTC"."SHOES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."SHOES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STRECKENPUNKTE
--------------------------------------------------------

  ALTER TABLE "OTC"."STRECKENPUNKTE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."STRECKENPUNKTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRACKTRAININGPROPERTY
--------------------------------------------------------

  ALTER TABLE "OTC"."TRACKTRAININGPROPERTY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."TRACKTRAININGPROPERTY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAINING
--------------------------------------------------------

  ALTER TABLE "OTC"."TRAINING" ADD PRIMARY KEY ("ID_TRAINING")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."TRAINING" MODIFY ("ID_FK_SHOES" NOT NULL ENABLE);
  ALTER TABLE "OTC"."TRAINING" MODIFY ("ID_FK_ATHLETE" NOT NULL ENABLE);
  ALTER TABLE "OTC"."TRAINING" MODIFY ("ID_TRAINING" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WEATHER
--------------------------------------------------------

  ALTER TABLE "OTC"."WEATHER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OTC"."WEATHER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HEALTH
--------------------------------------------------------

  ALTER TABLE "OTC"."HEALTH" ADD FOREIGN KEY ("ID_FK_ATHLETE")
	  REFERENCES "OTC"."ATHLETE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANUNGWOCHE
--------------------------------------------------------

  ALTER TABLE "OTC"."PLANUNGWOCHE" ADD FOREIGN KEY ("ID_FK_ATHLETE")
	  REFERENCES "OTC"."ATHLETE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROUTE
--------------------------------------------------------

  ALTER TABLE "OTC"."ROUTE" ADD FOREIGN KEY ("ID_FK_ATHLETE")
	  REFERENCES "OTC"."ATHLETE" ("ID") ENABLE;
  ALTER TABLE "OTC"."ROUTE" ADD FOREIGN KEY ("ID_FK_TRAINING")
	  REFERENCES "OTC"."TRAINING" ("ID_TRAINING") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOES
--------------------------------------------------------

  ALTER TABLE "OTC"."SHOES" ADD FOREIGN KEY ("ID_FK_ATHLETE")
	  REFERENCES "OTC"."ATHLETE" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRACKTRAININGPROPERTY
--------------------------------------------------------

  ALTER TABLE "OTC"."TRACKTRAININGPROPERTY" ADD FOREIGN KEY ("ID_FK_STRECKENPUNKT")
	  REFERENCES "OTC"."STRECKENPUNKTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAINING
--------------------------------------------------------

  ALTER TABLE "OTC"."TRAINING" ADD FOREIGN KEY ("ID_FK_WEATHER")
	  REFERENCES "OTC"."WEATHER" ("ID") ENABLE;
  ALTER TABLE "OTC"."TRAINING" ADD FOREIGN KEY ("ID_FK_ATHLETE")
	  REFERENCES "OTC"."ATHLETE" ("ID") ENABLE;
  ALTER TABLE "OTC"."TRAINING" ADD FOREIGN KEY ("ID_FK_SHOES")
	  REFERENCES "OTC"."SHOES" ("ID") ENABLE;
  ALTER TABLE "OTC"."TRAINING" ADD FOREIGN KEY ("ID_FK_ROUTE")
	  REFERENCES "OTC"."ROUTE" ("ID") ON DELETE SET NULL ENABLE;
