CREATE TABLE PUBLIC.ATHLETE (
	ID INTEGER NOT NULL,
	NAME VARCHAR(255),
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.HEALTH (
	ID INTEGER NOT NULL,
	WEIGHT INTEGER,
	CARDIO INTEGER,
	ID_FK_ATHLETE INTEGER,
	DATEOFMEASURE DATE,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.IMPORTED (
	ID INTEGER NOT NULL,
	ID_FK_ATHLETE INTEGER,
	IMPORTED_DATE TIMESTAMP,
	ACTIVITY_ID TIMESTAMP,
	COMMENTS VARCHAR(2147483647),
	ID_FK_WEATHER INTEGER,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.WEATHER (
	ID INTEGER NOT NULL,
	WETTER VARCHAR(2147483647),
	PRIMARY KEY (ID)
);

ALTER TABLE PUBLIC.HEALTH
	ADD FOREIGN KEY (ID_FK_ATHLETE) 
	REFERENCES OTC.PUBLIC.ATHLETE (ID);



ALTER TABLE PUBLIC.IMPORTED
	ADD FOREIGN KEY (ID_FK_ATHLETE) 
	REFERENCES OTC.PUBLIC.ATHLETE (ID);

ALTER TABLE PUBLIC.IMPORTED
	ADD FOREIGN KEY (ID_FK_WEATHER) 
	REFERENCES OTC.PUBLIC.WEATHER (ID);



CREATE INDEX PUBLIC.CONSTRAINT_157_INDEX_A ON PUBLIC.IMPORTED (ID_FK_ATHLETE);

CREATE INDEX PUBLIC.CONSTRAINT_7E_INDEX_A ON PUBLIC.HEALTH (ID_FK_ATHLETE);

CREATE INDEX PUBLIC.CONSTRAINT_INDEX_1 ON PUBLIC.IMPORTED (ID_FK_WEATHER);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_1 ON PUBLIC.ATHLETE (ID);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_7 ON PUBLIC.WEATHER (ID);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_A ON PUBLIC.IMPORTED (ID);

CREATE UNIQUE INDEX PUBLIC.PRIMARY_KEY_A42 ON PUBLIC.HEALTH (ID);